### ISSUE TITLE
Cannot download us_people_names.csv or stackoverflow-user-names.csv because of github data limits

### ISSUE THREAD

**Issue by JimmyCushnie** [aakashkag/People-Name-List#1]
![image](https://user-images.githubusercontent.com/32693298/78100398-abaf8080-73b2-11ea-9af7-62873e063e82.png)

Could you please host the data elsewhere, like google drive or dropbox?

**Comment by aakashkag** [comment]
you can following query in Google big query(https://console.cloud.google.com/bigquery) to download result.

SELECT first_name,display_name,age,gender FROM fh-bigquery.popular_names.stackoverflow_guesses

SELECT name,gender FROM bigquery-public-data.usa_names.usa_1910_current

SELECT author.name as author_name, author.email as author_email, committer.name as committer_name, committer.email as committer_email, repo_name FROM bigquery-public-data.github_repos.commits

SELECT * FROM fh-bigquery.popular_names.usa_summary_1880_2015


SELECT * FROM fh-bigquery.popular_names.gender_probabilities

SELECT * FROM fh-bigquery.freebase20140119.people_names
